import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,

  // Folders for organizing documents
  folders: defineTable({
    name: v.string(),
    color: v.string(),
    isPublic: v.boolean(),
    userId: v.string(),
    parentId: v.optional(v.id("folders")),
    deletedAt: v.optional(v.number()),
  })
    .index("by_userId", ["userId"])
    .index("by_isPublic", ["isPublic"])
    .index("by_parentId", ["parentId"])
    .index("by_deletedAt", ["deletedAt"]),

  // Documents (web links, PDFs, custom notes)
  documents: defineTable({
    type: v.union(v.literal("web"), v.literal("pdf"), v.literal("note")),
    title: v.string(),
    source: v.optional(v.string()),
    content: v.string(),
    excerpt: v.optional(v.string()),
    searchText: v.optional(v.string()),
    searchTagNames: v.optional(v.array(v.string())),
    searchFolderName: v.optional(v.string()),
    searchFolderLabel: v.optional(v.string()),
    searchSourceText: v.optional(v.string()),
    folderId: v.optional(v.id("folders")),
    userId: v.string(),
    deletedAt: v.optional(v.number()),
    isPublic: v.optional(v.boolean()),
    notebook: v.optional(v.string()),
    // AI-generated fields
    summary: v.optional(v.string()),
    summaryType: v.optional(v.string()),
    // Scraping status
    scrapingStatus: v.optional(
      v.union(
        v.literal("pending"),
        v.literal("processing"),
        v.literal("completed"),
        v.literal("failed"),
      ),
    ),
    scrapingError: v.optional(v.string()),
  })
    .index("by_userId", ["userId"])
    .index("by_folderId", ["folderId"])
    .index("by_userId_and_type", ["userId", "type"])
    .index("by_deletedAt", ["deletedAt"])
    .index("by_isPublic", ["isPublic"])
    .searchIndex("search_text", {
      searchField: "searchText",
      filterFields: ["userId"],
    }),

  // Tags for documents (auto-generated by AI)
  tags: defineTable({
    name: v.string(),
    userId: v.string(),
  })
    .index("by_userId", ["userId"])
    .index("by_name_and_userId", ["name", "userId"]),

  // Junction table for document-tag relationships
  documentTags: defineTable({
    documentId: v.id("documents"),
    tagId: v.id("tags"),
  })
    .index("by_documentId", ["documentId"])
    .index("by_tagId", ["tagId"]),

  // Chat messages for document-specific conversations
  chatMessages: defineTable({
    documentId: v.id("documents"),
    role: v.union(v.literal("user"), v.literal("assistant")),
    content: v.string(),
    userId: v.string(),
  }).index("by_documentId", ["documentId"]),
});
